### ISSUE TITLE
Using in TextWatcher

### ISSUE THREAD

**Issue by hatpick** [nulab/zxcvbn4j#10]
When I use .measure in my TextWatcher, it has a delay that freezes the app, any idea why is that?

**Comment by vvatanabe** [comment]
Thank you for the report.
I want to solve the problem with you. And I have some questions.

1. Is it android app?
2. Do you create a zxcvbn instance for each to measure the password strength?
3. If it's alright with you, please show me the code.

**Comment by hatpick** [comment]
Hello,

Yes, it is an Android app. Unfortunately I can't share the code, but I use only one instance. It seems that the first time I call measure, runtime delay is very long that freezes the app, so I had to use Threading, but still there is a delay between user typing the password and my indicator showing its strength.

**Comment by vvatanabe** [comment]
Hi hatpick.
I understood it. You 're using only one instance. And the problem (very long that freezes) is when to generate a first instance. I also think of a solution. Please wait for a while. Thank you.

**Comment by vvatanabe** [comment]
Hi hatpick.

I wrote a simple sample code to measure.
When measured with this code, delay of first instance generation is not a worry too much.
The following, paste the code and image.

### sample code
``` java
public class MainActivity extends AppCompatActivity implements TextWatcher {

    private static final Handler HANDLER = new Handler(Looper.getMainLooper());

    private static final Zxcvbn ZXCVBN = new Zxcvbn();

    private EditText editText;
    private ProgressBar progressBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        editText = (EditText)findViewById(R.id.edit_text);
        editText.setInputType(InputType.TYPE_CLASS_TEXT
        		| InputType.TYPE_TEXT_VARIATION_PASSWORD);
        editText.addTextChangedListener(this);
        progressBar = (ProgressBar) findViewById(R.id.progressbar_horizontal);
        progressBar.setMax(4);
        progressBar.setProgress(0);
    }

    @Override
    public void beforeTextChanged(CharSequence s, int start, int count, int after) {

    }

    @Override
    public void onTextChanged(CharSequence s, int start, int before, int count) {

    }

    @Override
    public void afterTextChanged(final Editable s) {
        MeasureTask task = new MeasureTask(progressBar);
        task.execute(s.toString());
    }

    private static class MeasureTask extends AsyncTask<String, Void, Void> {

        private final ProgressBar progressBar;

        public MeasureTask(ProgressBar progressBar) {
            this.progressBar = progressBar;
        }

        @Override
        protected Void doInBackground(String... params) {
            final Strength strength = ZXCVBN.measure(params[0]);
            MainActivity.HANDLER.post(new Runnable() {
                @Override
                public void run() {
                    int score = strength.getScore();
                    Log.d(MeasureTask.class.getName(), "score: " + score);
                    progressBar.setProgress(score);
                }
            });
            return null;
        }
    }
}
```

### sample image
![example_zxcvbn4j](https://cloud.githubusercontent.com/assets/9883589/13552477/b816f964-e3a8-11e5-8225-e6eea4a3c398.gif)

**Comment by hatpick** [comment]
Thanks, that's sort of what I'm doing right now.

**Comment by vvatanabe** [comment]
O.O.M...
Sorry, Not OOM in my device(Emulator).
If it's alright with you, please tell me spec of the device(Emulator).

**Comment by hatpick** [comment]
Fails on both:
343 RAM, VM Heap 32, Internal Storage 200, SD card 100 with API 16
1536 RAM, VM Heap 64, Internal Storage 200, SD card 100 with API 21

**Comment by vvatanabe** [comment]
Thank you for suggestions.
Exactly. When first dictionary generation, are consuming a lot of memory.
I'll think about reduce the memory cost of first dictionary generation !

**Comment by hatpick** [comment]
Good luck. I'll switch to a server side solution for now. Thanks.

**Comment by hatpick** [comment]
Hello,

I get an exception ```java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets```on devices with API 21-, I think you have used an API that is not available for them. It crashes them and I can test it.

**Comment by vvatanabe** [comment]
Hello, hatpick.

I have eliminated the java.nio.charset.StandardCharsets.
So, the exception is not thrown.
And, I was changed to minSdkVersion 8 of zxcvbn4j-example-android.

repo: https://github.com/vvatanabe/zxcvbn4j-example-android/releases
apk: https://github.com/vvatanabe/zxcvbn4j-example-android/releases/download/1.0.2/zxcvbn4j-example-android-1.0.2.apk

**Comment by hatpick** [comment]
Hello,

It works fine now.
