### ISSUE TITLE
The 2020s have not been supported on recent years' feedback

### ISSUE THREAD

**Issue by kxn4t** [nulab/zxcvbn4j#100]
The 1990s, 2000s, and 2010s are supported, but the 2020s do not seem to be supported.

It seems to be because it is not included in the regular expression of the matcher.
https://github.com/nulab/zxcvbn4j/blob/master/src/main/java/com/nulabinc/zxcvbn/matchers/RegexMatcher.java#L15

**Comment by vvatanabe** [comment]
@kxn4t Thanks for feedbacks! I think we should add 2021. This will make the result slightly different from the origin, but the decision to add 2021 will be correct.

**Comment by vvatanabe** [comment]
Done
