### ISSUE TITLE
 zxcvbn4j  over-estimates strength compared to JavaScript version

### ISSUE THREAD

**Issue by IvanPizhenko** [nulab/zxcvbn4j#105]
JavaScript:
```js
var zxcvbn = require('zxcvbn');
zxcvbn('2352523452bd dhf').guesses
```
prints:
```
21900100000000
```
Kotlin:
```
val z = Zxcvbn()
val m = z.measure("2352523452bd dhf", arrayListOf(*Constants.PASSWORD_WEAK_WORDS)).guesses.toLong()
println("$m")
```
prints
```
25185100000000
```
which is stronger

Is it correct? I'd expect Java version to produce same results as original JavaScript version, as long as this is positioned as port of original library to Java.

**Comment by IvanPizhenko** [comment]
any news here?

**Comment by vvatanabe** [comment]
We will investigate in the near future. But anyone's help is also welcome.

**Comment by vvatanabe** [comment]
@IvanPizhenko We have fixed this issue. Please try the new version 1.8.1.
https://github.com/nulab/zxcvbn4j/releases/tag/1.8.2
