### ISSUE TITLE
Seems to allow weak passwords

### ISSUE THREAD

**Issue by ewpreston** [nulab/zxcvbn4j#107]
Our security team is testing this and I'm getting a strength of 4 with the following password:

blackboardtester12345678910

That doesn't seem right to me. They are claiming that's a weak password and it looks pretty weak to me.

I can't use this library if it says that's a strong password

**Comment by nicoursi** [comment]
The following password is also reported as strong. I would therefore suggest to add it to password.txt or revise the algorithm as it belongs to a pattern.

aaaeeeiiiooouuuyyy

Related password:

aaeeiioouuyy
aeiouy
aaabbbcccddd

**Comment by vvatanabe** [comment]
This password's score is also determined to be 4 in the original dropbox/zxcvbn.

<img width="880" alt="image" src="https://github.com/nulab/zxcvbn4j/assets/9883589/9e5f573d-1f10-4477-b59a-39a25b10e819">

https://lowe.github.io/tryzxcvbn/

You can create a custom dictionary using the following method. Please adjust the evaluation logic by customizing it.
[Customize internal dictionaries and keyboards](https://github.com/nulab/zxcvbn4j#customize-internal-dictionaries-and-keyboards-1)
