### ISSUE TITLE
 Long passphrase scored with 0 and negative guesses

### ISSUE THREAD

**Issue by OffRange** [nulab/zxcvbn4j#109]
There is a issues with calculating the guesses of a password.
So if I have generated a passphrase, for example this:
`wondering-spotting-lai-journals-agrees-ngc-chief-kernel-accompanying-whom-png-numerical`
and insert it into the messures method, the score becomes 0 be because the guesses is negative: `-3.070036083570689E65`

**Comment by vvatanabe** [comment]
fixed #116
