### ISSUE TITLE
Score not matching with javascript version

### ISSUE THREAD

**Issue by jkunggit** [nulab/zxcvbn4j#129]
Hi, if I use a password such as "password@123". The Javascript version will return a score of 2. However, the Java version returns 1. There only seem to be a discrepancy with the @. If I type the same password "password_123" then both Javascript and Java will return 2. This is a major problem since I am trying to verify the on the backend and both scores should match.

**Comment by vvatanabe** [comment]
@jkunggit  
Sorry for the wait! It took longer than expected, but I was able to fix this issue! Please use version 1.8.1.
https://github.com/nulab/zxcvbn4j/releases/tag/1.8.1
