### ISSUE TITLE
NullPointerException when calculating score 

### ISSUE THREAD

**Issue by oversecio** [nulab/zxcvbn4j#19]
Hi,

I'm using Version 1.1.1 of your library, and a user has reported a crash and provided below stack trace.

I can't reproduce this problem myself, but it happened to the user, maybe you can have a look at it and see what's going on?

Regards,

Mark.

Stacktrace:
java.lang.NullPointerException: Attempt to read from field 'int com.nulabinc.zxcvbn.matchers.Match.i' on a null object reference
at com.nulabinc.zxcvbn.Scoring.unwind(SourceFile:101)
at com.nulabinc.zxcvbn.Scoring.mostGuessableMatchSequence(SourceFile:46)
at com.nulabinc.zxcvbn.Scoring.mostGuessableMatchSequence(SourceFile:20)
at com.nulabinc.zxcvbn.Zxcvbn.measure(SourceFile:30)
at com.nulabinc.zxcvbn.Zxcvbn.measure(SourceFile:14)

**Comment by vvatanabe** [comment]
Thank you for reporting. I was reproduce this problem.
If the characters size in a password is very large fails to measurement is thrown NPE.
The problem reproduce when result of "Scoring#bruteforceGuesses" is "Infinity".

Large password:
[large_password.txt](https://github.com/nulab/zxcvbn4j/files/495281/large_password.txt)

I will improve soon.

**Comment by vvatanabe** [comment]
@oversecio 
This problem has been resolved. Released version 1.1.5

**Comment by oversecio** [comment]
Thank You!
