### ISSUE TITLE
Progaurd

### ISSUE THREAD

**Issue by hatpick** [nulab/zxcvbn4j#24]
Hello,

Can you add the progaurd script for release builds, I get exception because it can't find your txt files (dictionaries, etc.)

**Comment by vvatanabe** [comment]
Hi.

I can't add the progaurd script for release builds. Because this library also using in Pure Java.
You can avoid the error by adding an ignore rule(following) to proguard.

```
-keep class com.nulabinc.zxcvbn.**    {*;}
```

**Comment by hatpick** [comment]
Got it, I already added that, I thought you may wanna have it here too, didn't realize it's Java not Android library.

**Comment by brainscript** [comment]
Why the heck is everyone here making the same typo? :smile:
It's »**ProGuard**«, not »**progaurd**« ...

**Comment by hatpick** [comment]
@brainscript while we are the grammar nazi topic: why the heck everyone here IS MAKING the same typo

**Comment by brainscript** [comment]
@hatpick My sentence was perfectly fine. I just placed the verb **»is«** _before_ the subject **»everyone«**.
You forgot **»at/on«** in your sentence, btw. **»While we are at/on the grammar nazi topic [...]«**

**Let's end this _"grammar war"_ here. :smiley_cat: :peace_symbol:**
