### ISSUE TITLE
Bug: Result is not accurate

### ISSUE THREAD

**Issue by guptankur** [nulab/zxcvbn4j#26]
When calculating strength of this password "abababababbbbbbbbbbbb" this gives the score 4. 
But if we increase/decrease 1 more character "b". it gives score 0.

But the https://dl.dropboxusercontent.com/u/209/zxcvbn/test/index.html always gives the correct result.

**Comment by vvatanabe** [comment]
Thank you for reporting. I'll investigate that problem.

**Comment by guptankur** [comment]
Hi @vvatanabe ,
Any news about the fix?

**Comment by vvatanabe** [comment]
@guptankur Sorry for the late reply. I will release that fix on weekends. Please wait.

**Comment by vvatanabe** [comment]
@guptankur I released a fix for this problem. Please try it.
https://github.com/nulab/zxcvbn4j/releases/tag/1.2.1
