### ISSUE TITLE
Inconsistent results when using keyboard pattern

### ISSUE THREAD

**Issue by gtRfnkN** [nulab/zxcvbn4j#32]
When using keyboard pattern this library (1.2.2) returns different results than the original (4.4.1)

For example: "xsw234rfvb" returns strength 3 with the java port but 2 with the js library. Same results for: "yaq123edc", "cde345tgbn", "yaqwedcvb" and many more.
Is there any way to make the two libraries consistent?

**Comment by vvatanabe** [comment]
@gtRfnkN I'm sorry for the late reply and thanks for the report! I will check this problem as soon as possible.

**Comment by vvatanabe** [comment]
@gtRfnkN
I fixed this problem and released it. Please check it! Thanks.

fixed: https://github.com/nulab/zxcvbn4j/releases/tag/1.2.3
