### ISSUE TITLE
Get crash on OnePlus 2 device

### ISSUE THREAD

**Issue by shunxingchen** [nulab/zxcvbn4j#33]
When using zxcvbn 1.2.2 dependency with Android studio:
Get RuntimeException when initiate Zxcvbn as new Zxcvbn(), found this on OnePlus 2 device

**Comment by vvatanabe** [comment]
@shunxingchen
Thanks for the report! I would like to know the version of Android OS and would you please give me the log containing stacktrace?

**Comment by shunxingchen** [comment]
The Android OS is 6.0.1 on OnePlus 2. I do not have log stack trace, the issue found from our production release. Now is fixed after merging your source and modify your resource loading codes:

from java codes:

Dictionary.class.getResourceAsStream(buildResourcePath(filename))

to Android codes:

ApplicationMain.getContext().getAssets().open("dictionarys/"+filename+EXT)

And also keyboard loading accordingly.

**Comment by vvatanabe** [comment]
fixed 1.3.3
