### ISSUE TITLE
Get NumberFormatException

### ISSUE THREAD

**Issue by shunxingchen** [nulab/zxcvbn4j#34]
When password using just a number (such as: '8604' ) string, then 'measure(password)' will return NumberFormatException

**Comment by vvatanabe** [comment]
@shunxingchen 
Is this problem occurring the same as device and OS of #33?

**Comment by shunxingchen** [comment]
Hi,
For dependency, our one user with oneplus 2 got crash when create instance,
then we merge your source codes and modify resources loading method in
Android way, then it works. However for password measure sometimes we got
numberformat exception if password is number string.

We would like to continue using your lib, so would be happy if you will
improve and inform us. Thanks!

Best regards,
Chen

**Comment by hatpick** [comment]
@vvatanabe I get this:
java.lang.NumberFormatException: For input string: "5
"

DateMatcher Line 41

**Comment by hatpick** [comment]
Related #49 check this out

**Comment by vvatanabe** [comment]
This issue has been fixed in version 1.3.0
