### ISSUE TITLE
Different Strength Score between IOS and Android.

### ISSUE THREAD

**Issue by thieusike** [nulab/zxcvbn4j#38]
Hi Guy,
I'm using for password on IOS and Android but I get difference result strength score.
In Android:
Zxcvbn zxcvbn = new Zxcvbn();
Strength strength = zxcvbn.measure("qweasde");
==> strength.getScore() == 1
In IOS:
result = [checkSecurityPW: passwordStrenth:@"qweasde"]
==> result.score == nil
Have I config wrong in there?
Could You guid me? 
Thanks.

**Comment by vvatanabe** [comment]
@thieusike 
The official zxcvbn (https://github.com/dropbox/zxcvbn) score seems to be 1.

**Comment by thieusike** [comment]
@vvatanabe 
I try to test on website using zxcvbn (https://apps.cygnius.net/passtest/; http://www.cs.ait.ac.th/~on/password2.html) score seems to be 0.

**Comment by vvatanabe** [comment]
@thieusike 
Are you checking with a mobile device?
Let's build an official zxcvbn for latest and try it directly.
BTW:
<img width="400" alt="2017-06-22 15 32 28" src="https://user-images.githubusercontent.com/9883589/27420311-461ec7f6-5760-11e7-87d4-efd22323dbdb.png">

**Comment by thieusike** [comment]
@vvatanabe ,
Yes, it's working correctly. But I think it's not newest.
I think I found the reason. I see in your source on git at file [dictionary. cradle] from line 13 to line 18. It's seem the line of the dictionary not full the file in folder [data] so the score result incorrectly.
Could You check it again?
Thanks
