### ISSUE TITLE
Suggestions about capitalization and all uppercase are never given

### ISSUE THREAD

**Issue by mazine** [nulab/zxcvbn4j#4]
Suggestions with IDs feedback.dictionary.suggestions.capitalization and feedback.dictionary.suggestions.allUppercase are never given because `match.token` is always low-cased.

**Comment by vvatanabe** [comment]
Hello , mazine.
Thank you for me a lot of suggestions and PR. Your idea is great!
Just now for the " l10n ", we also was thinking.
From a decision as soon as possible, please wait a little.

**Comment by mazine** [comment]
I've fixed this issue and refactored `MatchingTest` a little. As the test uses parameters a lot, I've changed it to be `@RunWith(Paramterized.class)`. This enables more precise problems detection if any occurs. And of course IntelliJ shows such tests as a cute tree with nice test naming.
