### ISSUE TITLE
Simple dictionary and spatial password checks returns wrong data

### ISSUE THREAD

**Issue by SirWojtek** [nulab/zxcvbn4j#43]
Let's consider two passwords:
* `qwerty`
* `dogdogdog`

In JS version of library, responses are:
![qwerty](https://user-images.githubusercontent.com/8425921/35022627-a500c636-fb82-11e7-9f0e-67ed14cd3025.png)
![dogdogdog](https://user-images.githubusercontent.com/8425921/35022626-a4cb3bec-fb82-11e7-90e3-420660d856c2.png)

But for `zxcvbnj4` results are:
### dogdogdog
* score: 3
* guess time: 100 / hour: centuries
* guess time: 10 / sec: 4 months
* guess time: 10k / sec: 3 hours
* guess time: 10B / sec: less than 1 sec

### qwerty
* score: 2
* guess time: 100 / hour: 8 years
* guess time: 10 / sec: 8 days
* guess time: 10k / sec: 11 minutes
* guess time: 10B / sec: less than 1 sec

**Comment by SirWojtek** [comment]
Actually, that was a bug in my code. Somehow all passwords I've passed have been wrapped with `""`. I've spent 3 hours trying to figure out that.

**Comment by vvatanabe** [comment]
@SirWojtek No problem. Thank you for using!
