### ISSUE TITLE
ResourceBundle.Control not supported in named modules

### ISSUE THREAD

**Issue by jmurph** [nulab/zxcvbn4j#45]
When running in Java 9 with the zxcvbn4j library on the module path (so it is an automatically named module), the following error is produced:
&nbsp;&nbsp;&nbsp;&nbsp;java.lang.UnsupportedOperationException: ResourceBundle.Control not supported in named modules

The relevant part of the stack trace is:
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.util.ResourceBundle.checkNamedModule(ResourceBundle.java:1537)
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1055)
&nbsp;&nbsp;&nbsp;&nbsp;at zxcvbn@1.2.3/com.nulabinc.zxcvbn.Feedback.resolveResourceBundle(Feedback.java:83)
&nbsp;&nbsp;&nbsp;&nbsp;at zxcvbn@1.2.3/com.nulabinc.zxcvbn.Feedback.getWarning(Feedback.java:64)
&nbsp;&nbsp;&nbsp;&nbsp;at zxcvbn@1.2.3/com.nulabinc.zxcvbn.Feedback.getWarning(Feedback.java:57)

**Comment by vvatanabe** [comment]
@jmurph  Thanks for letting me know.  I will investigate

**Comment by vvatanabe** [comment]
@jmurph We fixed this problem and released version 1.2.5. Please try again.
