### ISSUE TITLE
Bug:Inconsistent results

### ISSUE THREAD

**Issue by wysophiajy** [nulab/zxcvbn4j#48]
I test this password "gggggggggggggggghjklzxcv", the score is 4.
But, when I test on this website https://apps.cygnius.net/passtest/, the score is 2.
Could you help to resolve this problem?

**Comment by vvatanabe** [comment]
@wysophiajy 
Perhaps the version of zxcvbn used by this site is old. 

The score is 4 on the official website below.
https://lowe.github.io/tryzxcvbn/

**Comment by wysophiajy** [comment]
I see. Thanks for your help.
