### ISSUE TITLE
Inconsistent score between zxcvbn4j and zxcvbn

### ISSUE THREAD

**Issue by kyneh** [nulab/zxcvbn4j#50]
I get inconsistent scores for following values:

Password | zxcvbn4j score | zxcvbn score
--- | ---- | -----
5621127 | 2 | 1
61526611441 | 4 | 3
0078690420729 | 4 | 3

**Comment by StanKocken** [comment]
Thanks @kyneh, I would add as well `zhang198822`:
https://lowe.github.io/tryzxcvbn/ (zxcvbn score): 2 / 4
zxcvbn4j: 3 / 4

**Comment by TomLottermann** [comment]
Is there any news on this?
We're considering switching from nbvcxz since zxcvbn4j seems to be a more exact replica of zxcvbn.

**Comment by TomLottermann** [comment]
@vvatanabe: You were active last in this project. Do you maybe have an idea about where this difference might be coming from?

**Comment by vvatanabe** [comment]
@TomLottermann I'm not sure the cause. It may take some time to investigate.

**Comment by vvatanabe** [comment]
@TomLottermann 
We found the cause of the problem. I'll release a fix today.

**Comment by vvatanabe** [comment]
@kyneh @StanKocken @TomLottermann 
I fixed and released 1.3.1. Thanks!

**Comment by TomLottermann** [comment]
Wow that was fast!

Thanks a ton! :)
