### ISSUE TITLE
Could not initialize class com.nulabinc.zxcvbn.Matching

### ISSUE THREAD

**Issue by gaurav2895** [nulab/zxcvbn4j#58]
I have implemented this in the spring 5 web application. 

This is for version 1.2.6

Top level stack trace for reference:

java.lang.NoClassDefFoundError: Could not initialize class com.nulabinc.zxcvbn.Matching
                at com.nulabinc.zxcvbn.Zxcvbn.createMatching(Zxcvbn.java:45)
                at com.nulabinc.zxcvbn.Zxcvbn.measure(Zxcvbn.java:32)
                at com.nulabinc.zxcvbn.Zxcvbn.measure(Zxcvbn.java:15)

**Comment by vvatanabe** [comment]
I chk it asap!

**Comment by vvatanabe** [comment]
@gaurav2895
What Java version(and type) do you use? oraclejdk? openjdk? others?

**Comment by gaurav2895** [comment]
@vvatanabe It's Java 1.8 OpenJDK

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

**Comment by vvatanabe** [comment]
Thanks! I continue to investigate.

**Comment by gaurav2895** [comment]
@vvatanabe but when I downgrade the version to 1.2.5, it's working fine as expected

**Comment by vvatanabe** [comment]
Oh...

**Comment by anaclaudiar** [comment]
Same error for me, but I'm using 
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)

**Comment by vvatanabe** [comment]
Thank you for reporting!
We are currently fixing.

**Comment by vvatanabe** [comment]
@gaurav2895 @anaclaudiar @yasuyuki-baba 
Thanks for feadback and pull request.
We released the fixed version 1.2.7. Plz try it!

**Comment by gaurav2895** [comment]
@vvatanabe Thanks! It's working🤗
