### ISSUE TITLE
Provide possibility to add multiple user dictionaries

### ISSUE THREAD

**Issue by masooh** [nulab/zxcvbn4j#70]
With the second parameter of the measure method I can add another dictionary, but only one. For other languages it would be great to add multiple dictionaries.

To improve performance it would also be good to build the ranked dictionaries only once.

```java
List<String> german_surnames = new ArrayList();
german_surnames.add("müller");
List<String> german_words = new ArrayList();
german_words.add("der");

Zxcvbn zxcvbn = new Zxcvbn();
zxcvbn.addDictionary(german_surnames);
zxcvbn.addDictionary(german_words);
Strength strength = zxcvbn.measure("This is password");
```

**Comment by eicki** [comment]
Have you solved/implemented that feature? I'm missing the same.

**Comment by eicki** [comment]
https://github.com/nulab/zxcvbn4j/pull/90

**Comment by ManfredSchenkIOSB** [comment]
Any update on this issue? We would also like to use this feature. The library is useless if one cannot add language specific word lists for the target region.

**Comment by lumarino** [comment]
We adapted a feature to include custom dictionaries the way it was thought of be by the library itself by enabling the possibility to add more dictionary and keyboard files : https://github.com/1and1/zxcvbn4j/tree/make_resources_configurable I also created a PR for it but got no feedback yet: https://github.com/nulab/zxcvbn4j/pull/106

**Comment by lumarino** [comment]
@vvatanabe  can you give some feedback to his please? Is this project still maintained?

**Comment by vvatanabe** [comment]
Finally, we have released this feature to customize dictionaries and keyboards.

CHANGELOG:
https://github.com/nulab/zxcvbn4j/blob/master/CHANGELOG.md#170-2022-04-13

Usage:
https://github.com/nulab/zxcvbn4j#customize-internal-dictionaries-and-keyboards-1
