### ISSUE TITLE
Is this library thread-safe?

### ISSUE THREAD

**Issue by nobleach** [nulab/zxcvbn4j#71]
I'm considering using this on the backend as a challenge/response api endpoint. I can't see anywhere where there seems to be any local mutable state, but I might be missing something. Just wondering if others have used it like this?

**Comment by vvatanabe** [comment]
@nobleach
Do you want to encrypt the password with a challenge and response mechanism and measure the password strength in server?

**Comment by nobleach** [comment]
I plan on sending plain text to the server, and running `zxcvbn()` against it. I'd probably return a JSON response to the client with a few of the fields in it (crackTimeSeconds, score, suggestions, etc). Where I am concerned is if I were to start sending thousands of requests to this method. I would only encrypt the password if it meets the required criteria.

**Comment by vvatanabe** [comment]
@nobleach 
Sorry for the late reply. I was reviewing the code, just in case.
This library is thread-safe. Nulab use it as a server API, and We haven't any race conditions so far.

**Comment by nobleach** [comment]
Fantastic. Thank you!
