### ISSUE TITLE
Migrate GitHub Action

### ISSUE THREAD

**Issue by vvatanabe** [nulab/zxcvbn4j#74]
Thanks to Travis CI.

**Comment by overheadhunter** [comment]
I noticed that there hasn't been much activity lately. Is this due to lacking CI?

Having migrated several projects from Travis to GH Actions, may I offer my help?

**Comment by vvatanabe** [comment]
@overheadhunter Thanks! That's very helpful. I really appreciate that.

**Comment by overheadhunter** [comment]
The changes in this pull request reflect what you used to do in the `.travis.yml`. I hope this allows to continue development of this awesome library. We depend on it and would love to see some further improvements implemented and released soon! 🙂
