### ISSUE TITLE
Suggestions have default values with empty password

### ISSUE THREAD

**Issue by andrea07021981** [nulab/zxcvbn4j#75]
I found a behaviour and I am not sure if it’s made on purpose. If I call the measure method with an empty string, the strength object has these values:
- Score = 0
- Feedback/suggestions = “Use a few words, avoid common phrases” and “No need for symbols, digits, or uppercase letters.“.

Both are the default values, but since I entered an empty string I was expecting to find an empty suggestions array.
Could be a valid solution to give back an “Default” Strength status with no suggestions in case of empty password?

Thanks

**Comment by vvatanabe** [comment]
@andrea07021981 
This library maintains compatibility with dropbox/zxcvbn. So the results (scores and suggestions) of the empty string are the same as in dropbox/zxcvbn. That's the intended behavior.

Why don't you compare and validate the empty string before passing the value to the zxcvbn.measure method?

**Comment by andrea07021981** [comment]
@vvatanabe yes, I added this check about the empty string. I was just wondering whether it's a correct behaviour of the library or not.
Anyway, thank you, not I have understood.
Thanks
