### ISSUE TITLE
Bug in password strength checking

### ISSUE THREAD

**Issue by shubhamsinghrathi** [nulab/zxcvbn4j#77]
I just find out that "password_12345" is getting score 3, but in case of "password@12345" and "password$12345", I am getting 2 and 1 score respectively. In my opinion, all these passwords should receive only "1" score. I am using version 1.3.0

**Comment by vvatanabe** [comment]
@shubhamsinghrathi @knjk04

That is a very worrisome problem.

This library is just a port of zxcvbn. Therefore, compatibility is important to us.

I used tryzxcvbn to investigate the results of zxcvbn.
https://lowe.github.io/tryzxcvbn/

The result seems to be that compatibility is maintained.

![image](https://user-images.githubusercontent.com/9883589/105016077-8f85e880-5a85-11eb-89c9-663cc8509b18.png)

[Weak] `password$12345` matched two dictionary patterns. The strength is 1.

- `password$`:
  - Pattern: dictionary
  - Guesses Score: 3.84261
  - Rank: 2320
  - `$` character is replaced by an `s` as a leet character to form `passwords`. The most frequently used rank is 2320.
- `12345`:
  - Pattern: dictionary
  - Guesses Score: 1.69897
  - Rank: 6
  - Frequently used. Very dangerous.


[Fair] `password@12345` matched the dictionary and spatial patterns. The strength is 2.

- `password$`:
  - Pattern: dictionary
  - guesses score: 3.84261
  - rank: 2320
  - `$` is replaced by an `s` as a leet character to form `passwords`. 
  - It(`passwords`) is often used and has a rank of 2320.
- `12345`:
  - Pattern: dictionary
  - guesses score: 1.69897
  - rank: 6
  - Frequently used. Ranking 6. Very dangerous.

[Good] `password_12345` matched the dictionary pattern and the bruteforce pattern. The strength is 3.

- `password`:
  - Pattern: dictionary
  - guesses score: 1.69897
  - rank: 2
  - Frequently used. Ranking 2. Very dangerous.
- `_12345`:
  - Pattern: bruteforce
  - guesses score: 6
  - Brute force attacks to six-digit strings take a little longer.

These three passwords look the similar for humans, but when analyzed mechanically, they each have different characteristics.

**Comment by knjk04** [comment]
@vvatanabe Just to clarify, is this not an issue with zxcvbn (and therefore zxcvbn4j)?

**Comment by vvatanabe** [comment]
@knjk04 Yes, it's a specification, not an Issue.
