### ISSUE TITLE
Add tests verifying compatibility with JS

### ISSUE THREAD

**Issue by sambiomatters** [nulab/zxcvbn4j#8]
It's relatively easy to use Nashorn with zxcvbn javscript library. It would be beneficial to verify results from Java port against embedded JS version. Is this something you'd be interested in me creating a pull request for?

**Comment by vvatanabe** [comment]
I am very interested in this proposal. Be to test using the Nasuhon, would more accurate port can be realized. I want your PR. Could you please take care of it ?

**Comment by vvatanabe** [comment]
@sm4 I released a new version including this. Thanks!
https://github.com/nulab/zxcvbn4j/releases/tag/1.2.2
