### ISSUE TITLE
Two java.lang.NullPointerException

### ISSUE THREAD

**Issue by josmarlop16** [nulab/zxcvbn4j#93]
Hi, I´m using the latest version available, but when I want to run it, I'm getting this java.lang.NullPointerException at these two classes:
com.nulabinc.zxcvbn.ApproachComparisonTest > classMethod FAILED
    java.lang.NullPointerException at ApproachComparisonTest.java:220

com.nulabinc.zxcvbn.JavaPortTest > classMethod FAILED
    java.lang.NullPointerException at JavaPortTest.java:28
I've tried to fix it, but anyway I cannot do that. If you could just help me I would be really pleased. Thanks!!

**Comment by vvatanabe** [comment]
@josmarlop16 

Probably the following code is not getting the resource.
https://github.com/nulab/zxcvbn4j/blob/master/src/test/java/com/nulabinc/zxcvbn/ApproachComparisonTest.java#L219-L220

Maybe we need to use some other class loader to fall back on, like the following
https://github.com/nulab/zxcvbn4j/blob/master/src/main/java/com/nulabinc/zxcvbn/matchers/ResourceLoader.java#L23-L61

**Comment by vvatanabe** [comment]
DONE
https://github.com/nulab/zxcvbn4j/pull/128
